### ISSUE TITLE
Impossible to run recipe: ReferenceError: handleSourceFile is not defined

### ISSUE THREAD

**Issue by AnielloFalcone** [intuita-inc/codemod-registry#496] opened 2023-11-28 14:35 UTC
### Faulty codemod

`msw/2/upgrade-recipe`

### Actual code after transformation

```js
Executing the "msw/2/upgrade-recipe" codemod against "/Users/aniello.falcone/Developer/[package_path]"
Downloading the "msw/2/upgrade-recipe" codemod, not using cache
Downloading the "msw/2/imports" codemod, not using cache
Downloading the "msw/2/type-args" codemod, not using cache
Downloading the "msw/2/request-changes" codemod, not using cache
Downloading the "msw/2/ctx-fetch" codemod, not using cache
Downloading the "msw/2/req-passthrough" codemod, not using cache
Downloading the "msw/2/response-usages" codemod, not using cache
Downloading the "msw/2/callback-signature" codemod, not using cache
Downloading the "msw/2/lifecycle-events-signature" codemod, not using cache
Downloading the "msw/2/print-handler" codemod, not using cache
Running the "msw/2/upgrade-recipe" codemod using "recipe"
Running the "msw/2/imports" codemod using "ts-morph"
ReferenceError: handleSourceFile is not defined
ReferenceError: handleSourceFile is not defined
ReferenceError: handleSourceFile is not defined
ReferenceError: handleSourceFile is not defined
ReferenceError: handleSourceFile is not defined
ReferenceError: handleSourceFile is not defined
```

### Estimated severity

I don't know, but I can't run the recipe because every codemod gives the same error.

### Environment:

-   Intuita CLI version: 1.0.0-beta.1
-   OS: MacOS 14.0 (23A344)
-   Node.js version: v21.2.0

### Additional context

I have a monorepo and I tried to run the codemods both in the root of the repo and in the package I need to make the changes but nothing worked.
I have also installed globally ts-morph thinking I was missing it but I still get the same error.

**Comment by grzpab** [comment] 2023-11-28 16:48
@AnielloFalcone hello, thank you for creating an issue, we identified the problem and we have already come up with a fix, we should release it shortly.

**Comment by GeorgeWL** [comment] 2023-11-28 16:59
also seeing this exact same issue, Windows 10 Enterprise, build 19045.3693

**Comment by grzpab** [comment] 2023-11-28 17:02
@AnielloFalcone @GeorgeWL the issue is fixed in the most recent version of the CLI: https://www.npmjs.com/package/intuita (0.2.2) and also in the Intuita VSCode Extension.

**Closed** 2023-11-29 08:09 UTC

**Comment by AnielloFalcone** [comment] 2023-11-29 08:42
I just did the migration by hand, but great job guys, really thanks!!!

**Comment by mohab-sameh** [comment] 2023-11-29 10:30
@all-contributors add @AnielloFalcone for bug reporting
